package com.github.havardh.javaflow;

import static java.util.Arrays.asList;
import static java.util.Collections.singletonList;

import com.github.havardh.javaflow.phases.filetransform.CommentAppendTransformer;
import com.github.havardh.javaflow.phases.filetransform.EslintDisableTransformer;
import com.github.havardh.javaflow.phases.parser.java.JavaParser;
import com.github.havardh.javaflow.phases.reader.FileReader;
import com.github.havardh.javaflow.phases.transform.InheritanceTransformer;
import com.github.havardh.javaflow.phases.transform.SortedTypeTransformer;
import com.github.havardh.javaflow.phases.verifier.MemberFieldsPresentVerifier;
import com.github.havardh.javaflow.phases.writer.flow.FlowWriter;
import com.github.havardh.javaflow.phases.writer.flow.converter.Converter;
import com.github.havardh.javaflow.phases.writer.flow.converter.JavaFlowConverter;
import com.github.havardh.javaflow.util.TypeMap;

public class JavaFlow {

  public static void main(String args[]) {
    TypeMap typeMap = new TypeMap("types.yml");
    Converter converter = new JavaFlowConverter(typeMap);

    Execution execution = new Execution(
        new FileReader(),
        new JavaParser(),
        asList(
            new InheritanceTransformer(),
            new SortedTypeTransformer()
        ),
        singletonList(new MemberFieldsPresentVerifier(typeMap)),
        new FlowWriter(converter),
        asList(
            new CommentAppendTransformer("Generated by javaflow 1.1.0"),
            new EslintDisableTransformer(singletonList("no-use-before-define")),
            new CommentAppendTransformer("@flow")
        )
    );

    System.out.println(execution.run(args));
  }

}
